### ISSUE TITLE
authentification avec Google Sign-in

### ISSUE THREAD

**Issue by aubm** [matvdg/TuPreferes#11]
Pour utiliser l'application, l'utilisateur doit être authentifié par le biais de son compte Google.

Plus d'informations : https://developers.google.com/identity/sign-in/ios/start-integrating#before_you_begin

Détails à discuter ...

**Comment by matvdg** [comment]
à terme rajouter Facebook Auth

**Comment by matvdg** [comment]
après discussion avec le grand nain tracassin suprême (Sen) pas d'authentification pour utiliser l'app (cela effarerait les futures victimes du nain)
